import type { ProfileVarietyScope } from "@/lib/profile-elo-categories";

export const VARIETY_DAILY_ARTICLE_POOLS: Record<ProfileVarietyScope, string[]> = {
  minecraft: [
    "Minecraft",
    "Creeper",
    "Enderman",
    "Nether (Minecraft)",
    "Redstone",
    "Villager (Minecraft)",
    "Biome (Minecraft)",
    "Crafting",
    "Survival mode",
    "Creative mode",
    "Mojang Studios",
    "Notch",
    "Herobrine",
    "Diamond",
    "Obsidian",
  ],
  league: [
    "League of Legends",
    "Ahri",
    "Yasuo",
    "Jinx (League of Legends)",
    "Summoner (League of Legends)",
    "Riot Games",
    "MOBA",
    "Esports",
    "World Championship (League of Legends)",
    "Nexus (League of Legends)",
    "Baron Nashor",
    "Demacia",
    "Noxus",
    "Piltover",
    "Zaun",
  ],
  pokemon: [
    "Pokémon",
    "Pikachu",
    "Charizard",
    "Ash Ketchum",
    "Pokédex",
    "Pokémon Red and Blue",
    "Nintendo",
    "Game Freak",
    "Pokémon type",
    "Legendary Pokémon",
    "Eevee",
    "Mewtwo",
    "Gym Leader",
    "Pokémon Center",
    "Pokémon GO",
  ],
  "star-wars": [
    "Star Wars",
    "Luke Skywalker",
    "Darth Vader",
    "Death Star",
    "Yoda",
    "The Force",
    "Lightsaber",
    "Millennium Falcon",
    "Han Solo",
    "Princess Leia",
    "Jedi",
    "Sith",
    "Tatooine",
    "Galactic Empire (Star Wars)",
    "Rebel Alliance",
  ],
  marvel: [
    "Marvel Comics",
    "Spider-Man",
    "Iron Man",
    "Captain America",
    "Thor (Marvel Comics)",
    "Hulk",
    "Avengers (comics)",
    "X-Men",
    "Black Panther (character)",
    "Doctor Strange",
    "Wolverine (character)",
    "Stan Lee",
    "MCU",
    "Thanos",
    "Loki (Marvel Comics)",
  ],
};
